version: '3.4'
services:
  master:
    image: redis
    container_name: redis-master
    restart: always
    command: redis-server --port 6379
    #network_mode: "host"

  slave1:
    image: redis
    container_name: redis-slave-1
    restart: always
    command: redis-server --slaveof 172.16.81.145 6379 --port 6380
    #network_mode: "host"

  slave2:
    image: redis
    container_name: redis-slave-2
    restart: always
    command: redis-server --slaveof 172.16.81.145 6379 --port 6381
    #network_mode: "host"
